### ISSUE TITLE
FAVE-align dictionary check output

### ISSUE THREAD

**Issue by hilaryp** [JoFrhwld/FAVE#29]
Some transcript files are causing the FAVE-align dictionary check to produce garbage output text files, inserting null bytes like so:
![screen shot 2014-06-06 at 12 52 20 pm](https://cloud.githubusercontent.com/assets/1972246/3203376/42ea526c-ed9b-11e3-8900-95d843acc9c7.png)
(The rest of the file is like that, making it impossible to check most of the items.)

I'm not sure what's causing this problem, not all files I've run produce it. If anyone's interested in fixing this, I can send an example file.

**Comment by chrisbrickhouse** [comment]
Closing as stale. Please open a new issue if you are still having problems.
