### ISSUE TITLE
Error using nmake /f htk_htklib_nt.mkf all command

### ISSUE THREAD

**Issue by hamayounahmad** [JoFrhwld/FAVE#45]
Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        cl /nologo /c /ML /W0 /GX /O2 /G5 /Ob2 /D "NDEBUG" /D "WIN32" /D "_WINDOWS" /I "." /D "WIN32_AUDIO"  /D ARCH=\"WIN32\" /D "PHNALG" esig_asc.c
'cl' is not recognized as an internal or external command,
operable program or batch file.
NMAKE : fatal error U1077: 'cl' : return code '0x1'
Stop.

**Comment by hbake001** [comment]
I got the same issue here...using Visual Studio 2017

**Comment by egkogkou** [comment]
I got the same issue using Visual Studio 2015. Did anybody find a solution?

**Comment by chrisbrickhouse** [comment]
This is an error with HTK, not FAVE. Because HTK is no longer supported by its developers, we recommend using [the Montreal Forced Aligner](https://montreal-forced-aligner.readthedocs.io/en/latest/) for alignment. When using FAVE extract, you will want to use the `--mfa` command line option.
