### ISSUE TITLE
extractFormants.py cant find praat on ubuntu.

### ISSUE THREAD

**Issue by iveskins** [JoFrhwld/FAVE#46]
I got a path error when trying to run extractFormants.py 
due to these lines
```
    elif os.name == 'posix':
        PRAATNAME = 'Praat'

```
anyway I had to
`sudo ln -s /usr/bin/praat /usr/bin/Praat`
to get things working.

**Comment by efwb001** [comment]
Lifesaver! Alternately, this could be fixed by changing 'Praat' to 'praat' on that line, then manually specifying --speechSoftware praat (to override the parameter default of "Praat") when running.

**Comment by chrisbrickhouse** [comment]
@JoFrhwld this was fixed in #49 and can be closed

**Comment by iveskins** [comment]
I'll close this as looks like its resolved. @chrisbrickhouse
