### ISSUE TITLE
[RfC] Config file format

### ISSUE THREAD

**Issue by chrisbrickhouse** [JoFrhwld/FAVE#61]
Due to an oversight, fave-extract no longer accepts a config file; all user configuration is done via command line arguments. This is not user friendly to say the least and a configuration file should be added as a new feature in 2.1.0, but a question worth asking is what format this should take.

### Proposals
- YAML ([example](https://gist.github.com/chrisbrickhouse/070a5280581daae9fcbdb0830f9eba47#file-fave-config-proposal-yml))
- TSV ([example](https://gist.github.com/chrisbrickhouse/070a5280581daae9fcbdb0830f9eba47#file-fave-config-proposal-tsv))
- Old format ([example](https://gist.github.com/chrisbrickhouse/070a5280581daae9fcbdb0830f9eba47#file-fave-config-proposal-fcg))
- (other options?)

### Design considerations
Based on our current command line flags, we have 4 types of configuration option:
- Flags (false unless present)
- Single entry values (provide one value)
- Multiple entry values (provide a list of values)
- Filenames (similar to single entry values, but the file contains multiple values so best treated separately)
We want a format that is tailored to those, so a heavy emphasis on key:value systems is important. We only have one option where a list is important (`--stopWords`, multiple entry values) so this can be a second-class feature.

Additionally, we want the configuration file to be:
- Easy to read
- Simple to create
Which rules out a format like JSON which require a lot of extra typing and are not very readable.

Given the major version bump we are not *required* to maintain backwards compatibility, but it would be nice if possible. Unfortunately, this is unlikely as the old config format was just a wrapper around the command line arguments and so not very user friendly.

#### YAML
- ✔️ Good key-value support
- ✔️ Good list support
- ✔️ Easy to read
- ❓ Simple to create
- ❌ Backwards compatible (but we'd maintain the old version to avoid a 3.0 bump)

#### TSV
- ✔️ Good key-value support
- ❌ Good list support
- ✔️ Easy to read
- ✔️ Simple to create
- ❓ backwards compatible (if we build own parser)

#### Old 
- ✔️ Good key-value support
- ❌ Good list support
- ❌ Easy to read
- ❓ Simple to create
- ✔️ Backwards compatible

**Comment by chrisbrickhouse** [comment]
I'm torn between TSV and YAML. I'm not sure building our own TSV parser is a good idea given the maintenance burden, but doing so would allow us to incorporate older config files which is a big plus over YAML. However, I think the YAML syntax is a lot easier to parse, read, and create. It can be done in a text editor and uses `:` (a printing character) to separate values whereas TSV uses `\t` (a non-printing character, confusable with 4 spaces) and is best done in a spreadsheet.

**Comment by chrisbrickhouse** [comment]
After actually having to type up [these examples](https://gist.github.com/chrisbrickhouse/070a5280581daae9fcbdb0830f9eba47) I'm a big fan of the YAML. It's readable, and the only one where a stop word list actually looks nice. The issue whether end users would want to learn to use YAML, but it seems intuitive enough that a good documentation page could work.

**Comment by JoFrhwld** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [issue](https://trello.com/c/93ZnbKsP/3-issue)

**Comment by chrisbrickhouse** [comment]
In a call with Joe, we concluded that YAML would be the ideal format moving forward.
