### ISSUE TITLE
mean_stdv refactor

### ISSUE THREAD

**Issue by JoFrhwld** [JoFrhwld/FAVE#77]
The code in `mean_stdv()` should be refactored with numpy
https://github.com/JoFrhwld/FAVE/blob/ce2c5cfa2279f771e083532ce467db167f538873/fave/extractFormants.py#L1068

**Comment by chrisbrickhouse** [comment]
Good first issue:
-[] Write a test for the current output with lots of test cases
-[] Remove existing code and replace with numpy calls
-[] Ensure that the tests still pass, proving that the function output is identical

**Comment by DerMoehre** [comment]
Hi, 
I wrote a test for testing the existing code in extractFormants.py
It works locally, but fails if I try to create a pull request here on GitHub and somehow, it wants to add these code to the open pull request "Added badges to README". Is there a way to create another PR?

**Comment by JoFrhwld** [comment]
Closed with #84
