### ISSUE TITLE
restore praat scripts on feature/parselmouth-fix

### ISSUE THREAD

**Issue by JoFrhwld** [JoFrhwld/FAVE#89]
restore the following on `feature/parselmouth-fix`

```
praatScripts
├── extractFormants.praat
├── extractSegment.praat
├── getIntensity.praat
└──get_duration.praat
```

**Comment by chrisbrickhouse** [comment]
For future reference `git checkout master -- fave/praatScripts` restores the directory as it was in the 2.0.2 release on master. From there just commit and push as normal.
